### PR TITLE
Added option for changing stack size

### PR DESCRIPTION
**Pull request by ivan-egorov42**
According to #88.

### CODE REVIEW

**Comment by ivan-egorov42** [comment]
@Graur  @mximp pls, have a look. I changed `test_dataize` in order to check the functionality of stack size option of a compiler. I'm not sure if we need separate test for it, but if we need, I will add todo for it. 

I added a long list to the test for checking StackOveflow. Now we don't have StackOveflow in test due to stack size option which increases size of the stack.

**Review by Graur — APPROVED** [review]
@yegor256 please, have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@ivan-egorov42 thanks!

**Pull request merged**
