### PR TITLE
fix(#296): fixing home tag

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #296 

## PR-Codex overview
The focus of this PR is to update the `mvnw` function to accept additional flags based on the provided options, enhancing flexibility and customization.

### Detailed summary
- Added `flags` function to generate Maven flags based on options
- Updated `mvnw` function to include additional flags from options

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by yegor256** [comment]
@maxonfjvipon no test to reproduce this bug?

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.21.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.1`

**Pull request merged**
