### PR TITLE
docs.js now generates an empty file eodocs.html

### PR DESCRIPTION
**Pull request by SenjeyB**

### CODE REVIEW

**Comment by SenjeyB** [comment]
@yegor256 Can you take a look at this one, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@SenjeyB thanks!

**Comment by 0crat** [comment]
@SenjeyB It is [not a good idea](https://www.yegor256.com/2014/04/15/github-guidelines.html) to name Git branches the way you named this one: "`main`". You've earned -12 points. Next time, better give your branch the same name as the number of the ticket that you are solving. In this case, a perfect name, for example, would be "`439`".

**Pull request merged**
